.TH "extension\ezextrafeatures\autoloads" 3 "Thu Mar 15 2012" "Version 1.0.0-RC" "eZ Extra Features" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extension\ezextrafeatures\autoloads \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBeZExtraFeaturesTemplateOperators\fP"
.br
.RI "\fIClass operator to manage functions in template\&. \fP"
.ti -1c
.RI "class \fBeZJSFeaturesTemplateOperators\fP"
.br
.RI "\fIClass operator to manage functions in template\&. \fP"
.ti -1c
.RI "class \fBeZPHPFeaturesTemplateOperators\fP"
.br
.RI "\fIClass operator to manage functions in template\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for eZ Extra Features from the source code\&.
