.TH "C:/Users/aloyant/ezextrafeatures/ezextrafeatures/autoloads/ezphpfeaturestemplateoperators.php" 3 "Thu Mar 15 2012" "Version 1.0.0-RC" "eZ Extra Features" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aloyant/ezextrafeatures/ezextrafeatures/autoloads/ezphpfeaturestemplateoperators.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBextension\\ezextrafeatures\\autoloads\\eZPHPFeaturesTemplateOperators\fP"
.br
.RI "\fIClass operator to manage functions in template\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "namespace \fBextension\\ezextrafeatures\\autoloads\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for eZ Extra Features from the source code\&.
