.TH "C:/Users/aloyant/ezextrafeatures/ezextrafeatures/autoloads/eztemplateautoload.php" 3 "Thu Mar 15 2012" "Version 1.0.0-RC" "eZ Extra Features" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aloyant/ezextrafeatures/ezextrafeatures/autoloads/eztemplateautoload.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$eZTemplateOperatorArray\fP = array()"
.br
.ti -1c
.RI "\fB$eZTemplateOperatorArray\fP []"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$eZTemplateOperatorArray = array()"

.PP
Definition at line 7 of file eztemplateautoload\&.php\&.
.SS "$eZTemplateOperatorArray[]"
\fBInitial value:\fP
.PP
.nf
 array( 'script' => 'extension/ezextrafeatures/autoloads/ezextrafeaturestemplateoperators\&.php',
                                    'class' => 'extension\\ezextrafeatures\\autoloads\\eZExtraFeaturesTemplateOperators',
                                    'operator_names' => eZExtraFeaturesTemplateOperators::operators()
)
.fi
.PP
Definition at line 10 of file eztemplateautoload\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for eZ Extra Features from the source code\&.
