.TH "C:/Users/aloyant/ezextrafeatures/ezextrafeatures/settings/site.ini.append.php" 3 "Thu Mar 15 2012" "Version 1.0.0-RC" "eZ Extra Features" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aloyant/ezextrafeatures/ezextrafeatures/settings/site.ini.append.php \- 
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for eZ Extra Features from the source code\&.
